Host klone
  HostName klone.hyak.uw.edu
  User hamishiv

Host tillicum
  HostName tillicum.hyak.uw.edu
  User hamishiv

Host klone tillicum
  ControlMaster auto
  ControlPath ~/.ssh/control-%r@%h:%p
  ControlPersist 8h
  ServerAliveInterval 60
  ServerAliveCountMax 3
  Compression yes

# Restore the default scope for the including file.
Host *
